/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected.dashboard'
import { Route as ProtectedAdminRouteImport } from './routes/_protected.admin'
import { Route as ProtectedCoursesSlugRouteImport } from './routes/_protected.courses.$slug'
import { Route as ProtectedCoursesSlugLessonsLessonIdRouteImport } from './routes/_protected.courses.$slug_.lessons.$lessonId'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesSlugRoute = ProtectedCoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoursesSlugLessonsLessonIdRoute =
  ProtectedCoursesSlugLessonsLessonIdRouteImport.update({
    id: '/courses/$slug_/lessons/$lessonId',
    path: '/courses/$slug/lessons/$lessonId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/admin': typeof ProtectedAdminRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/courses/$slug/lessons/$lessonId': typeof ProtectedCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/admin': typeof ProtectedAdminRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/courses/$slug/lessons/$lessonId': typeof ProtectedCoursesSlugLessonsLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/mcp': typeof McpRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/_protected/courses/$slug_/lessons/$lessonId': typeof ProtectedCoursesSlugLessonsLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/admin'
    | '/dashboard'
    | '/courses/$slug'
    | '/courses/$slug/lessons/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/admin'
    | '/dashboard'
    | '/courses/$slug'
    | '/courses/$slug/lessons/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/mcp'
    | '/_protected/admin'
    | '/_protected/dashboard'
    | '/_protected/courses/$slug'
    | '/_protected/courses/$slug_/lessons/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  McpRoute: typeof McpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$slug': {
      id: '/_protected/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof ProtectedCoursesSlugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/courses/$slug_/lessons/$lessonId': {
      id: '/_protected/courses/$slug_/lessons/$lessonId'
      path: '/courses/$slug/lessons/$lessonId'
      fullPath: '/courses/$slug/lessons/$lessonId'
      preLoaderRoute: typeof ProtectedCoursesSlugLessonsLessonIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedCoursesSlugRoute: typeof ProtectedCoursesSlugRoute
  ProtectedCoursesSlugLessonsLessonIdRoute: typeof ProtectedCoursesSlugLessonsLessonIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedCoursesSlugRoute: ProtectedCoursesSlugRoute,
  ProtectedCoursesSlugLessonsLessonIdRoute:
    ProtectedCoursesSlugLessonsLessonIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  McpRoute: McpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
